#!/usr/bin/env bash

set -eu

BASE="$(dirname "$0")"
cd "$BASE"

export STORE=$(mktemp -d)

cat /dev/null | ../root.sh 3< get.json 4>&1
jo message=hai | ../root.sh 3< post.json 4<&1

ls -lh $STORE
cat $STORE/messages.json
